
---
openapi: 3.0.1
info:
  title: Affirm AppSec Was Here
  version: '1.0'
paths:
  "\n://example.com/Affirm/Appsec/Was/Here":
    post:
      tags:
      - Test
      parameters:
      - name: Affirm AppSec Was Here
